### ISSUE TITLE
PEAR installed APC has debugging enabled

### ISSUE THREAD

**Issue by leedo** [chef-cookbooks/php#102] opened 2014-11-24 23:31 UTC
I can't seem to track down how or why this is the case. When I run manually the `pear` command that should be getting run, it doesn't seem to have debugging enabled.

`echo -e '\r' | pear install -a apc`

However, when installed via chef-client, APC ends up with debugging enabled, which makes it not terribly useful.

**Comment by cheeseplus** [comment] 2017-02-21 18:58
Closing this one due to age but please open a new issue with distro specifics and a current reproduction case.

**Closed by cheeseplus** 2017-02-21 18:58 UTC
