### ISSUE TITLE
Install package versions

### ISSUE THREAD

**Issue by juliangut** [chef-cookbooks/php#208] opened 2017-06-01 09:56 UTC
### Cookbook version
Any

### Chef-client version
12

### Platform Details
CentOS 6

### Scenario:
Allow package version installation

__package receipe__:

```ruby
node['php']['packages'].each do |extension|
  package = extension.split(/@/)

  if package.length === 1
    package package[0] do
      options node['php']['package_options']
    end
  else
    package package[0] do
      version package[1]
      allow_downgrade true
      options node['php']['package_options']
    end
  end
end
```

__configuration__:

```json
"default_attributes": {
    "php": {
      "bin": "php",
      "ext_dir": "/usr/lib64/php/modules/",
      "fpm_package": "php-fpm",
      "fpm_service": "php-fpm",
      "packages": [
        "php",
        "php-process",
        "php-bcmath",
        "php-devel",
        "php-redis",
        "php-pear@1.10.3-1.el6.remi",
        "php-pecl-apcu@5.1.8-1.el6.remi.7.0",
        "php-pecl-memcached@3.0.3-1.el6.remi.7.0",
        "php-pecl-mongodb@1.2.9-1.el6.remi.7.0",
        "php-pecl-redis@3.1.2-1.el6.remi.7.0",
      ]
    }
  }
```

**Comment by iennae** [comment] 2017-09-26 06:23
Hi,

This appears to be a duplicate of #125. I'm closing this in favor of that issue.

**Closed by iennae** 2017-09-26 06:23 UTC
