### ISSUE TITLE
Fatal error on purging broken package.

### ISSUE THREAD

**Issue by dkinzer** [chef-cookbooks/php#82] opened 2014-08-09 19:13 UTC
I tried purging a pear package that did not properly install because the wrong extension config directory was supplied.  

```
php_pear 'oci8' do 
   action 'purge'
end  
```

The action failed with the following relevant stack trace:

```
[2014-08-09T18:58:37+00:00] FATAL: Stacktrace dumped to /var/chef/cache/chef-stacktrace.out      
[2014-08-09T18:58:37+00:00] DEBUG: ArgumentError: php_pear[oci8] (oracle-instantclient::php line 
ror: ArgumentError: wrong number of arguments (2 for 4)                                          
/tmp/vagrant-chef-3/chef-solo-1/cookbooks/php/providers/pear.rb:212:in `manage_pecl_ini'         
/tmp/vagrant-chef-3/chef-solo-1/cookbooks/php/providers/pear.rb:170:in `remove_package'          
/tmp/vagrant-chef-3/chef-solo-1/cookbooks/php/providers/pear.rb:181:in `purge_package'           
/tmp/vagrant-chef-3/chef-solo-1/cookbooks/php/providers/pear.rb:76:in `block (2 levels) in class_
```

**Comment by tas50** [comment] 2017-06-27 19:11
So I tried to reproduce this one and I added additional testing to the cookbook in 4.3.0 to do a install/remove/purge so we cover it all. Purge and remove are actually just aliases in the code now so this shouldn't be a thing anymore. Obviously it's been a while since this was filed and it was potentially very different at the time, but I'm pretty confident we can close this out now.

**Closed by tas50** 2017-06-27 19:11 UTC
Labels: Type: Bug
